MedNotes/Controllers/DataController.cs
using MedNotes.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace MedNotes.Controllers
{
    public class DataController : Controller
    {
        //Logger logger = LogManager.GetCurrentClassLogger();

        public JsonResult GetSummaryData()
        {
            try
            {
                // logger.Info("Get summary data...");
                List<SummaryModel> result = DataAccess.GetSummaries();
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                LogHelper.SaveLogInfo(string.Format("Exception: Error occured in NotesController controller ClientSummary Action: \r\n  {0}", ex.Message), ex.StackTrace);
                return new JsonResult();
            }
        }

        // GET: Data
        public JsonResult GetICD10Data(string note_id, string query_val)
        {
            try
            {
                int id;
                if (int.TryParse(note_id, out id))
                {
                    //   logger.Info("Get icd 10 data...");
                    List<ICD10Model> result = DataAccess.GetICD10(id, query_val);
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                    return new JsonResult();
            }
            catch (Exception ex)
            {
                LogHelper.SaveLogInfo(string.Format("Exception: Error occured in NotesController controller GetICD10Data Action: \r\n  {0}", ex.Message), ex.StackTrace);
                return new JsonResult();
            }
        }

        public JsonResult GetNLPData(string note_id)
        {
            try
            {
                int id;
                if (int.TryParse(note_id, out id))
                {
                    List<NLP_TableModel> result = DataAccess.Get_NLP_Records(id);
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                    return new JsonResult();
            }
            catch (Exception ex)
            {
                LogHelper.SaveLogInfo(string.Format("Exception: Error occured in NotesController controller GetNLPData Action: \r\n  {0}", ex.Message), ex.StackTrace);
                return new JsonResult();
            }
        }

        public JsonResult GetUnidentifiedData(string note_id)
        {
            try
            {
                int id;
                if (int.TryParse(note_id, out id))
                {
                    List<Unidentified_TableModel> result = DataAccess.Get_Unidentified_Records(id);
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                    return new JsonResult();
            }
            catch (Exception ex)
            {
                LogHelper.SaveLogInfo(string.Format("Exception: Error occured in NotesController controller GetUserData Action: \r\n  {0}", ex.Message), ex.StackTrace);
                return new JsonResult();
            }
        }

        [HttpPost]
        public void SaveData(string NLPData, string UserData, string note_id, string is_complete, string html_text)
        {
            try
            {
                DataAccess.StoreDataTransaction(NLPData, UserData, note_id, is_complete);
                FilesController.SaveHtmlFile(note_id, html_text);
            }
            catch (Exception ex)
            {
                LogHelper.SaveLogInfo(string.Format("Exception: Error occured in NotesController controller SaveData Action: \r\n  {0}", ex.Message), ex.StackTrace);
            }
        }

        public JsonResult GetClientsData()
        {
            try
            {
                List<PersonsAndClientsModel> result = DataAccess.GetClients();
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                LogHelper.SaveLogInfo(string.Format("Exception: Error occured in NotesController controller GetClientsData Action: \r\n  {0}", ex.Message), ex.StackTrace);
                return new JsonResult();
            }
        }

        public JsonResult GetPersonData(string note_id)
        {
            try
            {
                int id;
                if (int.TryParse(note_id, out id))
                {
                    List<PersonsAndClientsModel> result = DataAccess.GetPerson(id);
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else
                    return new JsonResult();
            }
          
            catch (Exception ex)
            {
                LogHelper.SaveLogInfo(string.Format("Exception: Error occured in NotesController controller GetPersonData Action: \r\n  {0}", ex.Message), ex.StackTrace);
                return new JsonResult();
            }
        }

    }
}

MedNotes/Controllers/FilesController.cs
using MedNotes.Models;
using System;
using System.IO;
using System.Web;
using System.Web.Mvc;
using word = Microsoft.Office.Interop.Word;
using iTextSharp.text.pdf;
using iTextSharp.text.pdf.parser;
using System.Text;
using iTextSharp.text.html.simpleparser;
using System.Collections.Generic;
using Microsoft.Office.Interop.Word;
using System.Configuration;

namespace MedNotes.Controllers
{
    public class FilesController : Controller
    {
        // GET: Files
        public ActionResult ViewFile(string note_id)
        {
            int parsed_note_id;
            FileStreamResult fsResult = null;

            try
            {
                if (int.TryParse(note_id, out parsed_note_id))
                {
                    string html_file_name = DataAccess.GetHtmlFileName(parsed_note_id).Trim();
                    string output_notes_html_folder = ConfigurationManager.AppSettings["output_notes_html_folder"];
                    string html_path = System.IO.Path.Combine(output_notes_html_folder, html_file_name);
                    string mimeType = "text/html";

                    var fileStream = new FileStream(html_path,
                                              FileMode.Open,
                                              FileAccess.Read
                                            );

                    fsResult = new FileStreamResult(fileStream, mimeType);
                }
            }
            catch (Exception ex)
            {
                fsResult = null;
                LogHelper.SaveLogInfo(string.Format("Exception: {0}", ex.Message), ex.StackTrace);
                return null;
            }
            return fsResult;
        }

        public static void SaveHtmlFile(string note_id, string html_text)
        {
            int parsed_note_id;

            try
            {
                if (int.TryParse(note_id, out parsed_note_id))
                {
                    string html_file_name = DataAccess.GetHtmlFileName(parsed_note_id).Trim();
                    string output_notes_html_folder = ConfigurationManager.AppSettings["output_notes_html_folder"];
                    string output_html_path = System.IO.Path.Combine(output_notes_html_folder, html_file_name);

                    System.IO.File.WriteAllText(output_html_path, html_text);

                }
            }
            catch (Exception ex)
            {
                LogHelper.SaveLogInfo(string.Format("Exception: {0}", ex.Message), ex.StackTrace);
            }
        }

        public ActionResult ViewFile_Old(string note_id)
        {
            //  LogHelper.SaveLogInfo(string.Format("Start reading notes file for note_id = {0}", note_id));

            FileStreamResult fsResult = null;
            List<NLP_TableModel> nlp_html_result = null;

            word.Application app = null;
            word.Document doc = null;

            int parsed_note_id;
            string HTML_FileName = "Notes_Temp.htm";
            string mimeType = "text/html";
            string tempPath = ConfigurationManager.AppSettings["Temp_Files_Path"];
            string html_path = System.IO.Path.Combine(tempPath, HTML_FileName);

            if (int.TryParse(note_id, out parsed_note_id))
            {
                try
                {
                    string FileName = DataAccess.GetHtmlFileName(parsed_note_id).Trim();
                    nlp_html_result = DataAccess.Get_NLP_HTML_Highlight(parsed_note_id);

                    if (!string.IsNullOrEmpty(FileName))
                    {

                        string file_path = System.IO.Path.Combine(Server.MapPath("~/Content/Files/"), FileName);

                        FileInfo info = new FileInfo(FileName);

                        string extension = info.Extension;

                        if (extension == ".pdf")
                        {
                            string html_text = ExtractTextFromPdf(file_path, nlp_html_result);
                            System.IO.File.WriteAllText(html_path, html_text);
                        }
                        else if (extension == ".txt")
                        {
                            string text = System.IO.File.ReadAllText(file_path);
                            System.IO.File.WriteAllText(html_path, TextToHtml(text, nlp_html_result));
                        }
                        else if (extension == ".docx" || extension == ".doc")
                        {
                            app = new word.Application();
                            doc = app.Documents.Open(file_path);

                            doc.SaveAs2(html_path, word.WdSaveFormat.wdFormatText);
                            doc.Close();
                            app.Quit();

                            string text = System.IO.File.ReadAllText(html_path);
                            System.IO.File.WriteAllText(html_path, TextToHtml(text, nlp_html_result));

                        }

                    }

                    var fileStream = new FileStream(html_path,
                                            FileMode.Open,
                                            FileAccess.Read
                                          );

                    fsResult = new FileStreamResult(fileStream, mimeType);

                }
                catch (Exception ex)
                {
                    if (doc != null) doc.Close();
                    if (app != null) app.Quit();
                    fsResult = null;
                    LogHelper.SaveLogInfo(string.Format("Exception: {0}", ex.Message), ex.StackTrace);
                    return null;
                }
            }
            return fsResult;
        }

        private string TextToHtml(string text, List<NLP_TableModel> nlp_html_result)
        {
            text = HttpUtility.HtmlEncode(text);
            text = text.Replace("\r\n", "\r");
            text = text.Replace("\n", "\r");
            text = text.Replace("\r", "<br>\r\n");
            text = text.Replace("  ", " &nbsp;");

            text = addHighlight(text, nlp_html_result);

            return text;
        }

        private string ExtractTextFromPdf(string path, List<NLP_TableModel> nlp_html_result)
        {
            ITextExtractionStrategy its = new iTextSharp.text.pdf.parser.LocationTextExtractionStrategy();

            using (PdfReader reader = new PdfReader(path))

            {
                StringBuilder text = new StringBuilder();

                for (int i = 1; i <= reader.NumberOfPages; i++)

                {
                    string thePage = PdfTextExtractor.GetTextFromPage(reader, i, its);

                    thePage = addHighlight(thePage, nlp_html_result);

                    string[] theLines = thePage.Split('\n');

                    foreach (var theLine in theLines)

                    {
                        text.AppendLine(theLine + "</br>");
                    }
                }

                return text.ToString();
            }

        }

        private string addHighlight(string text, List<NLP_TableModel> nlp_html_result)
        {
            foreach (var item in nlp_html_result)
            {
                if (item != null)
                {
                    if (!string.IsNullOrEmpty(item.Nlp_Rejected_Descr))
                        text = text.Replace(item.Nlp_Rejected_Descr, "<a id=\"id_rej\" onclick=\"linkClicker(this);\" data-toggle=\"tooltip\" data-placement=\"bottom\" title=\"Dx Rejected\"  style=\"text-decoration: underline; font-weight:bold; color:red; cursor: pointer;user-select: none;-moz-user-select: none; -ms-user-select: none;  \">" + item.Nlp_Rejected_Descr + "</a>");
                    else
                    {
                        if (item.Nlp_Flag == "A")
                        {
                            text = text.Replace(item.Nlp_Accepted_Descr, "<a id=\"id_acc\" onclick=\"linkClicker(this);\" data-toggle=\"tooltip\" data-placement=\"bottom\" title=\"Dx Accepted\" style=\"text-decoration: underline; font-weight:bold; color:black; cursor: pointer;user-select: none;-moz-user-select: none; -ms-user-select: none;  \">" + item.Nlp_Accepted_Descr + "</a>");
                        }
                        else if (item.Nlp_Flag == "U" && !string.IsNullOrEmpty(item.Related_text))
                        {
                            text = text.Replace(item.Related_text, "<a id=\"id_add\"  onclick=\"linkClicker(this);\" data-toggle=\"tooltip\" data-placement=\"bottom\" title=\"Dx Added\" style=\"text-decoration: underline; font-weight:bold; color:#0BABC8; cursor: pointer;\">" + item.Related_text + "</a>");
                        }
                        else
                        {
                            text = text.Replace(item.Nlp_Accepted_Descr, "<a id=\"id_nm\" onclick=\"linkClicker(this);\" data-toggle=\"tooltip\" data-placement=\"bottom\" title=\"Dx not marked\" style=\"text-decoration: underline; font-weight:bold; color:green; cursor: pointer;user-select: none;-moz-user-select: none; -ms-user-select: none;  \">" + item.Nlp_Accepted_Descr + "</a>");
                        }
                    }
                }
            }

            text += @"<script type='text/javascript'>function linkClicker(obj){  localStorage.setItem('clicked_dx', obj.innerHTML); }</script>";
            return text;
        }


        private void FindAndReplace(Microsoft.Office.Interop.Word.Application doc, object findText, object replaceWithText)
        {
            //options
            object matchCase = false;
            object matchWholeWord = true;
            object matchWildCards = false;
            object matchSoundsLike = false;
            object matchAllWordForms = false;
            object forward = true;
            object format = false;
            object matchKashida = false;
            object matchDiacritics = false;
            object matchAlefHamza = false;
            object matchControl = false;

MedNotes/Controllers/NotesController.cs
using MedNotes.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace MedNotes.Controllers
{
    public class NotesController : Controller
    {
        public ActionResult Summary()
        {
           // LogHelper.SaveLogInfo("Med Notes start");
           // LogHelper.SaveLogInfo("Retrieve summary data");
            return View();

        }

        public ActionResult Setup()
        {
            //LogHelper.SaveLogInfo("Opening setup page");
            ViewBag.Message = "Setup page.";

            return View();
        }

        public ActionResult Details(int? note_id)
        {
            try
            {
                //LogHelper.SaveLogInfo(string.Format("Opening Details page with note_id = {0}", note_id));
                ViewBag.NoteId = note_id;
               // throw new Exception("test jsoin exception message");
                return View();
            }
            catch (Exception ex)
            {
                LogHelper.SaveLogInfo(string.Format("Exception: Error occured in NotesController controller in Details Action: \r\n  {0}", ex.Message), ex.StackTrace);
                return Json(new { status = "error", message = ex.Message });
            }
        }
    }
}

MedNotes/Views/Notes/Details.cshtml
@{
    ViewBag.Title = "Details";
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/Scripts/DataTables/js")
    @Styles.Render("~/Content/DataTables/css")
    @Scripts.Render("~/bundles/Scripts")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div id="details_menu">
                <form>
                    <div class="form-group frm_grp_extend col-xs-1 col-md-1">
                        <input type="text" hidden id="patient_id">
                        <label for="mrn" class="control-label" style="color:aliceblue">MRN</label>
                        <input type="text" value='' class="form-control frm_ctrl_h_extend" id="mrn" placeholder="MRN" disabled>
                    </div>
                    <div class="form-group frm_grp_extend col-xs-3 col-md-3">
                        <label for="person" class="control-label" style="color:aliceblue">Person</label>
                        <input type="text" value='' class="form-control frm_ctrl_h_extend" id="person" placeholder="Person" disabled>
                    </div>
                    <div class="form-group frm_grp_extend col-xs-1 col-md-1">
                        <label for="dob" class="control-label" style="color:aliceblue">DOB</label>
                        <input type="text" value='' class="form-control frm_ctrl_h_extend" id="dob" placeholder="DOB" disabled>
                    </div>
                    <div class="form-group frm_grp_extend col-xs-1 col-md-1">
                        <label for="age" class="control-label" style="color:aliceblue">Age</label>
                        <input type="text" value='' class="form-control frm_ctrl_h_extend" id="age" placeholder="Age" disabled>
                    </div>
                    <div class="form-group frm_grp_extend col-xs-1 col-md-1">
                        <label for="gender" class="control-label" style="color:aliceblue">Gender</label>
                        <input type="text" value='' class="form-control frm_ctrl_h_extend" id="gender" placeholder="Gender" disabled>
                    </div>
                    <div class="form-group frm_grp_extend col-xs-2 col-md-2">
                        <label for="race" class="control-label" style="color:aliceblue">Race</label>
                        <input type="text" value='' class="form-control frm_ctrl_h_extend" id="race" placeholder="Race" disabled>
                    </div>
                    <div class="form-group frm_grp_extend col-xs-3 col-md-2">
                        <label for="provider" class="control-label" style="color:aliceblue">Provider name</label>
                        <input type="text" value='' class="form-control frm_ctrl_h_extend" id="provider" placeholder="Provider" disabled>
                    </div>
                    <div class="form-group frm_grp_extend col-xs-1 col-md-1">
                        <label for="note_date" class="control-label" style="color:aliceblue">Note Date</label>
                        <input type="text" value='' class="form-control frm_ctrl_h_extend" id="note_date" placeholder="Note Date" disabled>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="container body-content">

        <div class="container" style="margin-top:2%">

            <input hidden id="noteId" data-value="@ViewBag.NoteId" />
            <input hidden type="text" class="input-sm" id="linkTxt" />

            <div style="float:left; width:50%;">
                <div style="height:3vh;" class="input-group add-on">
                    <input type="text" class="form-control" style="height:34px" placeholder="Search text in all documents....." name="srch-term" id="srch_val">
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit" id="btn_doc_search"><i class="glyphicon glyphicon-search"></i></button>
                    </div>
                </div>
                <div style="height:79vh; border:outset 1.8px">
                    <iframe src='@Url.Action("ViewFile", "Files", new {note_id = ViewBag.NoteId})' id="frame" style="width:100%; height:95%; border:outset 1px"></iframe>
                    <img src="~/Content/Icons/Dx_colors.png" alt="legend" style="width:55%; height:3.1%; border:outset 1px" />
                </div>
            </div>

            <div style="float:right; width:50%; height: 82vh; padding-left:5px; overflow: scroll; overflow-x: hidden; border:outset 1.8px">

                <table id="tbl_NLP_Diagnosis" class="table table-striped">
                    <thead>
                        <tr>
                            <th id="Status" class="padding_nlp_th_ext" style="width:18%;">Status</th>
                            <th id="Confidence" class="padding_nlp_th_ext" style="width:82%;">
                                <span class="fakeCell_conf">Confidence</span><span class="fakeCell_icd10">&nbsp;&nbsp;ICD10</span><span class="fakeCell_descr">&nbsp;Description</span>
                            </th>
                        </tr>
                    </thead>
                </table>

                <div>
                    <b style="float:left;">
                        Added Diagnosis
                    </b>
                    <table style="margin-top:3px;" id="tbl_User_Diagnosis" class="table table-striped">
                        <thead>
                            <tr>
                                <th class="padding_nlp_th_ext" id="ICD10">ICD10 / Description</th>
                            </tr>
                        </thead>
                    </table>
                </div>

            </div>
        </div>

        <div class="form-group" style="margin-top:1%; margin-bottom:1%">
            <div style="margin-left:36%">
                <div style="display: inline-block;">
                    <input type="checkbox" name="fancy-checkbox-success" id="fancy-checkbox-success" autocomplete="off" checked />
                    <div class="[ btn-group ]">
                        <label for="fancy-checkbox-success" class="[ ext_btn btn btn-success ]">
                            <span class="[ glyphicon glyphicon-ok ]"></span>
                            <span> </span>
                        </label>
                        <label for="fancy-checkbox-success" class="[ ext_btn btn btn-default]">Complete</label>
                    </div>
                </div>
                <button id="btnOK" class="btn btn-primary" type="button">Save</button>
                <button id="btnCancel" class="btn" type="button">Cancel</button>
            </div>
        </div>

    </div>


    <div class="modal fade" id="DescModal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 id="txt_header" class="modal-title"></h4>
                </div>
                <div class="modal-body">
                    <div class="row dataTable padding_nlp_th_ext">
                        <textarea id="txt_area" rows="3" cols="150"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal" aria-hidden="true">Close</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->


    <div class="modal fade" id="DocsModal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 id="docs_txt_header" class="modal-title"></h4>
                </div>
                <div class="modal-body">
                    <table id="tbl_patient_files" class="table table-striped" style="width:100%">
                        <thead>
                            <tr>
                                <th></th>
                                <th>File</th>
                                <th>Date</th>
                                <th>Entries</th>
                            </tr>
                        </thead>
                    </table>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal" aria-hidden="true">Close</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->

    <script src="~/Scripts/Notes/Details.js"></script>

    <div id="queryGetICD10" data-request-url="@Url.Action("GetICD10Data", "Data")"></div>
    <div id="saveDataOnServer" data-request-url="@Url.Action("SaveData", "Data")"></div>
    <div id="queryGetNLPData" data-request-url="@Url.Action("GetNLPData", "Data")"></div>
    <div id="queryGetUnidentifiedData" data-request-url="@Url.Action("GetUnidentifiedData", "Data")"></div>
    <div id="GoToSummary" data-request-url="@Url.Action("Summary", "Notes")"></div>
    <div id="queryGetPersonData" data-request-url="@Url.Action("GetPersonData", "Data")"></div>
    <div id="searchInHtmlFiles" data-request-url="@Url.Action("SearchValueInHtmlFiles", "Files")"></div>
    <div id="queryDetails" data-request-url='@Url.Action("Details", "Notes", new {note_id = "_id_"})'></div>

</body>

</html>

MedNotes/Views/Notes/Setup.cshtml
@{
    ViewBag.Title = "Setup";
}
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>